# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - master  # Run on pull requests targeting the master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check formatting
      run: |
        # stop the build if there are formatting is error in any python codes
        # to check whether the codes are formatted or not before merge
        pip install black==24.4.2
        pip install click==8.1.7
        python -m black -t py310 --check .
    - name: Test with pytest
      run: |
        export FCM_TEST_PROJECT_ID=test
        pip install . ".[test]"
        python -m pytest .
